language: python
python:
  - "2.6"
  - "2.7"
node_js:
  - "0.10"
env:
  # Test against the latest version of Twisted.
  - TWISTED_VERSION="Twisted"
matrix:
  include:
    # Test against the oldest version of Twisted that we claim to support
    # This is a separate matrix inclusion to avoid spawning unnecessary builds.
    - python: "2.7"
      env: TWISTED_VERSION="Twisted==13.1.0"
cache:
  directories:
    - wheelhouse
services:
  - riak
  - redis-server
before_install:
  - sudo apt-get install -y protobuf-compiler
install:
  - "mkdir wheelhouse"
  - "pip install wheel"
  - "pip wheel --find-links=wheelhouse --wheel-dir=wheelhouse ${TWISTED_VERSION} coveralls"
  - "pip wheel --find-links=wheelhouse --wheel-dir=wheelhouse -e ."
  - "pip install --use-wheel --find-links=wheelhouse ${TWISTED_VERSION} coveralls"
  - "pip install --use-wheel --find-links=wheelhouse -r requirements.pip"
script:
  - VUMITEST_REDIS_DB=1 VUMI_TEST_NODE_PATH="$(which node)" coverage run --source=vumi `which trial` vumi
after_success:
  - coveralls
