language: python
python:
  - "2.6"
  - "2.7"
node_js:
  - "0.10"
env:
  # Test against the latest version of Twisted.
  - TWISTED_VERSION="Twisted"
matrix:
  include:
    # Test against the oldest version of Twisted that we claim to support
    # This is a separate matrix inclusion to avoid spawning unnecessary builds.
    - python: "2.7"
      env: TWISTED_VERSION="Twisted==13.1.0"
services:
  - riak
  - redis-server
install:
  # We easy_install a binary riak_pb package because pip install needs `protoc'.
  - "pip install ${TWISTED_VERSION}"
  - "easy_install 'riak_pb<1.3.0'"
  - "pip install -r requirements.pip --use-wheel"
  - "pip install coveralls --use-wheel"
  - "python setup.py install"
script:
  - VUMITEST_REDIS_DB=1 VUMI_TEST_NODE_PATH="$(which node)" coverage run --source=vumi `which trial` vumi
after_success:
  - coveralls
