language: python
python:
  # - "2.6"
  - "2.7"
services:
  - riak
install:
  - "easy_install riak_pb"
#   - "pip install -r requirements.pip --use-mirrors"
#   - "python setup.py install"
# script: trial vumi
script: ./travis_riak_hack.sh
