sudo: false # We want container builds.

language: python
python:
  - "2.6"
  - "2.7"
node_js:
  - "0.10"
env:
  # Test against the latest version of Twisted using Riak 1.4.
  - TWISTED_VERSION="Twisted" RIAK_VERSION="1.4.12"
matrix:
  include:
    # Test against the oldest version of Twisted that we claim to support.
    # Also test against Riak 2.1.1.
    # This is a separate matrix inclusion to avoid spawning unnecessary builds.
    # Although there are two different things we're testing against here, they
    # are orthogonal and any failures should be easily attributable to either
    # Twisted version or Riak version without adding an additional build job.
    - python: "2.7"
      env: TWISTED_VERSION="Twisted==13.1.0" RIAK_VERSION="2.1.1"
    # Test on pypy without coverage, because it's unnecessary and very slow.
    # Also, we hit an obscure GC bug in pypy<=2.6.0 so we need at least 2.6.1.
    - python: "pypy"
      env: PYPY_VERSION="2.6.1" NO_COVERAGE=1 TWISTED_VERSION="Twisted" RIAK_VERSION="1.4.12"

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/downloads
services:
  - redis-server

before_install:
  # If necessary, set up an appropriate version of pypy.
  - if [ ! -z "$PYPY_VERSION" ]; then source utils/setup-pypy-travis.sh; fi
  # Set up an appropriate version of Riak.
  - utils/setup_travis_riak.sh "${RIAK_VERSION}"
install:
  # Travis seems to have pip 6.x, which doesn't build and cache wheels.
  - "pip install 'pip>=7.1.0'"
  - "pip install ${TWISTED_VERSION}"
  - "pip install -r requirements.pip"
  - "pip install coveralls"

before_script:
  # To see what version of Riak we're running and check that it's happy.
  - $HOME/riak/bin/riak version
  - $HOME/riak/bin/riak-admin member-status
script:
  - if [ -z "$NO_COVERAGE" ]; then COVERAGE_CMD="coverage run --source=vumi"; else COVERAGE_CMD=""; fi
  - VUMI_TEST_ASSERT_CLOSED=true VUMI_TEST_TIMEOUT=20 VUMITEST_REDIS_DB=1 VUMI_TEST_NODE_PATH="$(which node)" $COVERAGE_CMD `which trial` vumi

after_success:
  - if [ -z "$NO_COVERAGE" ]; then coveralls; fi
