language: python
python:
  - "2.6"
  - "2.7"
node_js:
  - "0.10"
services:
  - riak
  - redis-server
install:
  # We easy_install a binary riak_pb package because pip install needs `protoc'.
  - "easy_install 'riak_pb<1.3.0'"
  - "pip install -r requirements.pip --use-wheel"
  - "pip install coveralls --use-wheel"
  - "python setup.py install"
script:
  - VUMITEST_REDIS_DB=1 coverage run --source=vumi `which trial` vumi
after_success:
  - coveralls
