language: python
python:
  - "2.6"
  - "2.7"
services:
  - riak
  - redis-server
install:
  # We easy_install a binary riak_pb package because pip install needs `protoc'.
  - "easy_install 'riak_pb<1.3.0'"
  - "pip install -r requirements.pip --use-mirrors"
  - "python setup.py install"
script: VUMITEST_REDIS_DB=1 trial vumi
