# The unique name of this transport
TRANSPORT_NAME: smpp_transport_1

system_id: smppclient1  # username
password: password      # password
host: localhost         # the host to connect to
port: 2775              # the port to connect to

exchange_name: vumi.topic   # the AMQ exchange name
exchange_type: topic        # the AMQ exchange type
