system_id: smppclient2
password: password
host: localhost
port: 2773

interface_version: "34"
dest_addr_ton: 1
dest_addr_npi: 1
registered_delivery: 1

TRANSPORT_NAME: smppclient2

# Number Recognition
COUNTRY_CODE: "27"

OPERATOR_NUMBER:
    NETWORK1: "27761234567"
    NETWORK2: "27762234567"
    NETWORK3: "27763234567"

OPERATOR_PREFIX:
    27:
        27761: NETWORK1
        27762: NETWORK2
        27763: NETWORK3
        27764: NETWORK1