system_id: smppclient1
password: password
host: localhost
port: 2775
# system_type: smpp account if clickatell

# Clickatell required defaults
interface_version: "34"
dest_addr_ton: 1
dest_addr_npi: 1
registered_delivery: 1

# TRANSPORT_NAME: Clickatell
TRANSPORT_NAME: SmppClient1

# Number Recognition
COUNTRY_CODE: "27"

OPERATOR_NUMBER:
    NETWORK1: "27761234561"
    NETWORK2: "27761234562"
    NETWORK3: "27761234563"

